### ISSUE TITLE
XML definitions not generating

### ISSUE THREAD

**Issue by sufyanpat** [Healthedata1/IG-Template2#2]
I've set the showXML to true in the _config.yml file and it creates the XML tab (albeit, out of alignment) but it does not create the xml.html file.

**Comment by Healthedata1** [comment]
Oops, I threw another switch in the definitions.csv to strip out all the
fragments for a quicker build.   in definitions.csv  'onlyJson' should be
set to 'FALSE'  if you are using this file and the script to generate the
ig.json and ig.xml files that should fix it.
Otherwise, I made a new commit and pushed it to the repo.

Eric

Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, CA 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by sufyanpat** [comment]
Thank you! Works like a charm. Closing issue.

**Comment by sufyanpat** [comment]
Thank you that resolved it.
Just a side question…is there a setting to hide the element constraints?

[cid:image002.jpg@01D53346.2DA2F800]

Regards
Sufyan

**Comment by Healthedata1** [comment]
element constraints?   can you send screenshot of what you mean?

Eric

Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, CA 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com
